package com.travel.daily.traveldaily.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACCOUNT_BEAN".
 */
public class AccountBean {

    private Long id;
    private String imgUrl;
    private String name;
    private String detail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AccountBean() {
    }

    public AccountBean(Long id) {
        this.id = id;
    }

    public AccountBean(Long id, String imgUrl, String name, String detail) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.name = name;
        this.detail = detail;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
