package com.travel.daily.traveldaily.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BILL_LIST".
 */
public class BillList {

    private String key;
    private String billList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BillList() {
    }

    public BillList(String key) {
        this.key = key;
    }

    public BillList(String key, String billList) {
        this.key = key;
        this.billList = billList;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getBillList() {
        return billList;
    }

    public void setBillList(String billList) {
        this.billList = billList;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
