package com.travel.daily.traveldaily.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BILL_LIST".
 */
public class BillList {

    private Long id;
    private String billList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BillList() {
    }

    public BillList(Long id) {
        this.id = id;
    }

    public BillList(Long id, String billList) {
        this.id = id;
        this.billList = billList;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillList() {
        return billList;
    }

    public void setBillList(String billList) {
        this.billList = billList;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
