package com.travel.daily.traveldaily.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BILL_BEAN".
 */
public class BillBean {

    private Long id;
    private String imgUrl;
    private String detail;
    private Float price;
    private Long time;
    private String name;
    private String subBill;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BillBean() {
    }

    public BillBean(Long id) {
        this.id = id;
    }

    public BillBean(Long id, String imgUrl, String detail, Float price, Long time, String name, String subBill) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.detail = detail;
        this.price = price;
        this.time = time;
        this.name = name;
        this.subBill = subBill;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubBill() {
        return subBill;
    }

    public void setSubBill(String subBill) {
        this.subBill = subBill;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
