package com.travel.daily.traveldaily.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.travel.daily.traveldaily.dao.SceneryBeanDao;
import com.travel.daily.traveldaily.dao.HotelBeanDao;
import com.travel.daily.traveldaily.dao.DelicacyBeanDao;
import com.travel.daily.traveldaily.dao.BillBeanDao;
import com.travel.daily.traveldaily.dao.AccountBeanDao;
import com.travel.daily.traveldaily.dao.ImageBeanDao;
import com.travel.daily.traveldaily.dao.BillListDao;
import com.travel.daily.traveldaily.dao.DetailImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SceneryBeanDao.createTable(db, ifNotExists);
        HotelBeanDao.createTable(db, ifNotExists);
        DelicacyBeanDao.createTable(db, ifNotExists);
        BillBeanDao.createTable(db, ifNotExists);
        AccountBeanDao.createTable(db, ifNotExists);
        ImageBeanDao.createTable(db, ifNotExists);
        BillListDao.createTable(db, ifNotExists);
        DetailImageDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SceneryBeanDao.dropTable(db, ifExists);
        HotelBeanDao.dropTable(db, ifExists);
        DelicacyBeanDao.dropTable(db, ifExists);
        BillBeanDao.dropTable(db, ifExists);
        AccountBeanDao.dropTable(db, ifExists);
        ImageBeanDao.dropTable(db, ifExists);
        BillListDao.dropTable(db, ifExists);
        DetailImageDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SceneryBeanDao.class);
        registerDaoClass(HotelBeanDao.class);
        registerDaoClass(DelicacyBeanDao.class);
        registerDaoClass(BillBeanDao.class);
        registerDaoClass(AccountBeanDao.class);
        registerDaoClass(ImageBeanDao.class);
        registerDaoClass(BillListDao.class);
        registerDaoClass(DetailImageDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
