package com.travel.daily.traveldaily.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.travel.daily.traveldaily.dao.SceneryBean;
import com.travel.daily.traveldaily.dao.HotelBean;
import com.travel.daily.traveldaily.dao.DelicacyBean;
import com.travel.daily.traveldaily.dao.BillBean;
import com.travel.daily.traveldaily.dao.AccountBean;
import com.travel.daily.traveldaily.dao.ImageBean;
import com.travel.daily.traveldaily.dao.BillList;

import com.travel.daily.traveldaily.dao.SceneryBeanDao;
import com.travel.daily.traveldaily.dao.HotelBeanDao;
import com.travel.daily.traveldaily.dao.DelicacyBeanDao;
import com.travel.daily.traveldaily.dao.BillBeanDao;
import com.travel.daily.traveldaily.dao.AccountBeanDao;
import com.travel.daily.traveldaily.dao.ImageBeanDao;
import com.travel.daily.traveldaily.dao.BillListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sceneryBeanDaoConfig;
    private final DaoConfig hotelBeanDaoConfig;
    private final DaoConfig delicacyBeanDaoConfig;
    private final DaoConfig billBeanDaoConfig;
    private final DaoConfig accountBeanDaoConfig;
    private final DaoConfig imageBeanDaoConfig;
    private final DaoConfig billListDaoConfig;

    private final SceneryBeanDao sceneryBeanDao;
    private final HotelBeanDao hotelBeanDao;
    private final DelicacyBeanDao delicacyBeanDao;
    private final BillBeanDao billBeanDao;
    private final AccountBeanDao accountBeanDao;
    private final ImageBeanDao imageBeanDao;
    private final BillListDao billListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sceneryBeanDaoConfig = daoConfigMap.get(SceneryBeanDao.class).clone();
        sceneryBeanDaoConfig.initIdentityScope(type);

        hotelBeanDaoConfig = daoConfigMap.get(HotelBeanDao.class).clone();
        hotelBeanDaoConfig.initIdentityScope(type);

        delicacyBeanDaoConfig = daoConfigMap.get(DelicacyBeanDao.class).clone();
        delicacyBeanDaoConfig.initIdentityScope(type);

        billBeanDaoConfig = daoConfigMap.get(BillBeanDao.class).clone();
        billBeanDaoConfig.initIdentityScope(type);

        accountBeanDaoConfig = daoConfigMap.get(AccountBeanDao.class).clone();
        accountBeanDaoConfig.initIdentityScope(type);

        imageBeanDaoConfig = daoConfigMap.get(ImageBeanDao.class).clone();
        imageBeanDaoConfig.initIdentityScope(type);

        billListDaoConfig = daoConfigMap.get(BillListDao.class).clone();
        billListDaoConfig.initIdentityScope(type);

        sceneryBeanDao = new SceneryBeanDao(sceneryBeanDaoConfig, this);
        hotelBeanDao = new HotelBeanDao(hotelBeanDaoConfig, this);
        delicacyBeanDao = new DelicacyBeanDao(delicacyBeanDaoConfig, this);
        billBeanDao = new BillBeanDao(billBeanDaoConfig, this);
        accountBeanDao = new AccountBeanDao(accountBeanDaoConfig, this);
        imageBeanDao = new ImageBeanDao(imageBeanDaoConfig, this);
        billListDao = new BillListDao(billListDaoConfig, this);

        registerDao(SceneryBean.class, sceneryBeanDao);
        registerDao(HotelBean.class, hotelBeanDao);
        registerDao(DelicacyBean.class, delicacyBeanDao);
        registerDao(BillBean.class, billBeanDao);
        registerDao(AccountBean.class, accountBeanDao);
        registerDao(ImageBean.class, imageBeanDao);
        registerDao(BillList.class, billListDao);
    }
    
    public void clear() {
        sceneryBeanDaoConfig.getIdentityScope().clear();
        hotelBeanDaoConfig.getIdentityScope().clear();
        delicacyBeanDaoConfig.getIdentityScope().clear();
        billBeanDaoConfig.getIdentityScope().clear();
        accountBeanDaoConfig.getIdentityScope().clear();
        imageBeanDaoConfig.getIdentityScope().clear();
        billListDaoConfig.getIdentityScope().clear();
    }

    public SceneryBeanDao getSceneryBeanDao() {
        return sceneryBeanDao;
    }

    public HotelBeanDao getHotelBeanDao() {
        return hotelBeanDao;
    }

    public DelicacyBeanDao getDelicacyBeanDao() {
        return delicacyBeanDao;
    }

    public BillBeanDao getBillBeanDao() {
        return billBeanDao;
    }

    public AccountBeanDao getAccountBeanDao() {
        return accountBeanDao;
    }

    public ImageBeanDao getImageBeanDao() {
        return imageBeanDao;
    }

    public BillListDao getBillListDao() {
        return billListDao;
    }

}
