package com.travel.daily.traveldaily.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DETAIL_IMAGE".
 */
public class DetailImage {

    private Long id;
    private String pic0;
    private String pic1;
    private String pic2;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DetailImage() {
    }

    public DetailImage(Long id) {
        this.id = id;
    }

    public DetailImage(Long id, String pic0, String pic1, String pic2) {
        this.id = id;
        this.pic0 = pic0;
        this.pic1 = pic1;
        this.pic2 = pic2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPic0() {
        return pic0;
    }

    public void setPic0(String pic0) {
        this.pic0 = pic0;
    }

    public String getPic1() {
        return pic1;
    }

    public void setPic1(String pic1) {
        this.pic1 = pic1;
    }

    public String getPic2() {
        return pic2;
    }

    public void setPic2(String pic2) {
        this.pic2 = pic2;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
