package com.travel.daily.traveldaily.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DELICACY_BEAN".
 */
public class DelicacyBean {

    private Long id;
    private String imgUrl;
    private String title;
    private String detail;
    private Float price;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DelicacyBean() {
    }

    public DelicacyBean(Long id) {
        this.id = id;
    }

    public DelicacyBean(Long id, String imgUrl, String title, String detail, Float price) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.title = title;
        this.detail = detail;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
