package com.travel.daily.traveldaily.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IMAGE_BEAN".
 */
public class ImageBean {

    private String imgUrl;
    private byte[] pic;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImageBean() {
    }

    public ImageBean(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public ImageBean(String imgUrl, byte[] pic) {
        this.imgUrl = imgUrl;
        this.pic = pic;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public byte[] getPic() {
        return pic;
    }

    public void setPic(byte[] pic) {
        this.pic = pic;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
